### ISSUE TITLE
control plane rolling upgrades on spec changes

### ISSUE THREAD

**Issue by smira** [siderolabs/cluster-api-control-plane-provider-talos#107]
Control Plane provider should support rolling out new set of control plane machines on `spec` changes (similar to `MachineDeployment` controller and kubeadm control plane provider):

* `Version` (Kubernetes version)
* `InfrastructureTemplate`

E.g. see this code from kubeadm provider: 

https://github.com/kubernetes-sigs/cluster-api/blob/cefc044b286676bf5f04a9b3e9009eb93c2a5329/controlplane/kubeadm/internal/controllers/upgrade.go#L33-L34

**Comment by Preisschild** [comment]
One issue currently still existing is that a rollout is not triggered if you edit the talosconfig (`.spec.controlPlaneConfig`) in your `TalosControlPlane` resource.

It is only triggered if you edit the infrastructureRef (`.spec.infrastructureTemplate`) or kubernetes version (`spec.version`)

**Comment by smira** [comment]
Hm... That deserves a separate issue 😉

**Comment by smira** [comment]
kubelet supports taints via its config: https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/

and Talos provides a way to add extra config for the kubelet. 

I'm going to close this issue, as it is unrelated and actually fixed in CACPPT, so let's move this to the new issue/Slack/discussion if it needs further investigation, thank you.
