### ISSUE TITLE
Bootstrap backoff loop not 20 seconds

### ISSUE THREAD

**Issue by andrewrynhard** [siderolabs/cluster-api-control-plane-provider-talos#109]
This code seems to have a bug in it. Bootstrapping a cluster gets stuck in a backoff loop but it shouldn't because the `RetryAfter` is set to 20 seconds:

https://github.com/talos-systems/cluster-api-control-plane-provider-talos/blob/d6d9c022a5f9253f201e17717d1abc703076da19/controllers/taloscontrolplane_controller.go#L228-L242

Here is the error I am getting:

https://github.com/talos-systems/cluster-api-control-plane-provider-talos/blob/d6d9c022a5f9253f201e17717d1abc703076da19/controllers/taloscontrolplane_controller.go#L888-L890

**Comment by smira** [comment]
do you have full logs please?

**Comment by smira** [comment]
Should be fixed in v0.5.0-alpha.2
