### ISSUE TITLE
Use externalIPs when bootstrapping cluster if no InternalIP found for the node

### ISSUE THREAD

**Issue by Unix4ever** [siderolabs/cluster-api-control-plane-provider-talos#130]
Some infra providers (like Hetzner) do not set InternalIPs in the `Machine` resource.
We may need to have a fallback in the provider which will pick ExternalIPs if no InternalIPs were found on any of the nodes.

This logic should be updated:
https://github.com/siderolabs/cluster-api-control-plane-provider-talos/blob/master/controllers/taloscontrolplane_controller.go#L411

**Comment by damdo** [comment]
+1 for this.

@Unix4ever Would you prefer:
A)
- Try to pick an InternalIP from any of the machines
- If no InternalIP is found on any machine, try to pick an ExternalIP from any machine
- If no address is found on any machine throw an error

or
B)
- Try to pick an InternalIP from the first machine
- If no InternalIP is found on the first machine, try to pick an ExternalIP from the first machine
- If no *IP is found for the first machine, repeat the two steps above for the next machine
- If no address is found on any machine throw an error

**Comment by Unix4ever** [comment]
Current logic is that it checks if any of machines do not have InternalIP set.
It should remain the same, so the idea will be:

- iterate over the list of the machines.
- try to pick InternalIP from the machine.
- if InternalIP not found, try ExternalIP.
- if no IP found for **any** of the machines throw an error.
