### ISSUE TITLE
V0.5.2 breaks backwards compatibility with older machine configs 

### ISSUE THREAD

**Issue by AlvesAlexander** [siderolabs/cluster-api-control-plane-provider-talos#177]
### Description
When spinning up clusters with talos version <1.5.0 and provider version 0.5.2 the below error is seen in the sidero controller manager and the node is unable to pull a machine config.  downgrading to 0.5.1 the node is able to pull its machine config as intended.

### Logs
`2023/08/19 05:04:23 failure creating config struct: unknown keys found during decoding:
machine:
    features:
        diskQuotaSupport: true`

**Comment by smira** [comment]
CACPPT doesn't generate the machine configuration for Talos, it's the job of CABPT.

In turn, [CABPT](https://github.com/siderolabs/cluster-api-bootstrap-provider-talos/#usage) relies on `talosVersion:` field to keep the proper compatibility for older versions of Talos.

So this field should be set to match a proper release series of Talos, e.g. `v1.4`. If not set, or set to ahead of Talos version, the error like above will happen.
